import { Noto_Sans } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';

const noto = Noto_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  return (
    <html lang={params.lang}>
      <AppRouterCacheProvider>
        <body className={noto.className}>{children}</body>
      </AppRouterCacheProvider>
    </html>
  );
}
